"""Remove unique constraint from vendor email

Revision ID: <your_new_revision_id>
Revises: 799954dffc34
Create Date: 2025-09-09 13:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '<your_new_revision_id>' # Important: Keep the ID generated in your filename
down_revision = '799954dffc34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        # The key change is dropping the unique constraint on the email column.
        # Alembic for SQLite handles this by recreating the table without the constraint.
        batch_op.drop_constraint('uq_vendor_email', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        # This will reinstate the unique constraint if you ever need to revert.
        batch_op.create_unique_constraint('uq_vendor_email', ['email'])

    # ### end Alembic commands ###