"""Change Quote model to be file-based

Revision ID: 6cdb1cd827c9
Revises: 49c944191cc5
Create Date: 2025-09-08 14:17:58.810114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cdb1cd827c9'
down_revision = '49c944191cc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=255), nullable=False))
        batch_op.drop_column('amount')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.FLOAT(), nullable=False))
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
