"""Make Quote status nullable

Revision ID: 9283892d6db2
Revises: 15a64a82d793
Create Date: 2025-10-21 04:56:44.423184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9283892d6db2'
down_revision = '15a64a82d793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_json', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_follow_up_sent', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('preferred_vendor', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.drop_column('preferred_vendor')
        batch_op.drop_column('last_follow_up_sent')

    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    op.drop_table('push_subscription')
    # ### end Alembic commands ###
