"""Make Quote status nullable

Revision ID: 9283892d6db2
Revises: 15a64a82d793 # <<-- Make sure this points to the correct previous migration ID
Create Date: 2025-10-21 10:00:00.000000 # <<-- Adjust if needed

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9283892d6db2'
# IMPORTANT: Update this 'down_revision' to match the actual previous migration ID in your project.
# Based on the error log, the previous migration seems to be '15a64a82d793'.
# If you have other migrations between '15a64a82d793' and '9283892d6db2', adjust accordingly.
down_revision = '15a64a82d793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        # This is the only change needed in this migration file
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_nullable=False, # Specify original nullable status for downgrade
               existing_server_default=sa.text("'Pending'::character varying")) # Specify original default if applicable

    # REMOVED: The op.create_table('push_subscription', ...) block was here

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # REMOVED: The op.drop_table('push_subscription') block was here

    with op.batch_alter_table('quote', schema=None) as batch_op:
        # Revert the status column nullability
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_nullable=True, # Specify original nullable status for upgrade
               existing_server_default=sa.text("'Pending'::character varying")) # Specify original default if applicable

    # ### end Alembic commands ###