# migrations/versions/9e7f6f1c2b3a_add_approved_quote_id_to_work_order.py
"""Add approved_quote_id to WorkOrder

Revision ID: 9e7f6f1c2b3a
Revises: 5405132813c1
Create Date: 2025-09-16 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e7f6f1c2b3a'
down_revision = '5405132813c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_quote_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_work_order_approved_quote_id_quote', 'quote', ['approved_quote_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.drop_constraint('fk_work_order_approved_quote_id_quote', type_='foreignkey')
        batch_op.drop_column('approved_quote_id')

    # ### end Alembic commands ###