"""Add website to Vendor model

Revision ID: ba2403e3eb41
Revises: 6cdb1cd827c9
Create Date: 2025-09-08 16:34:28.478581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba2403e3eb41'
down_revision = '6cdb1cd827c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.drop_column('website')

    # ### end Alembic commands ###
