"""Add signature field to user model

Revision ID: bca71c0f1ad0
Revises: d781d8aa2370
Create Date: 2025-09-09 04:28:59.660221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bca71c0f1ad0'
down_revision = 'd781d8aa2370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_quote_attachment_id', ['attachment_id'])


    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature', sa.Text(), nullable=True))

    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.alter_column('wo_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.alter_column('wo_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('signature')

    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
