# migrations/versions/your_new_revision_id_add_follow_up_date_to_work_order.py
"""Add follow_up_date to WorkOrder

Revision ID: 22c608b1a2a9
Revises: 9e7f6f1c2b3a
Create Date: 2025-09-18 13:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c608b1a2a9'
down_revision = '9e7f6f1c2b3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follow_up_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.drop_column('follow_up_date')

    # ### end Alembic commands ###